/**
 * Official Monetag TMA (Telegram Mini App) Rewarded Ad Integration Service
 * 
 * Handles loading Monetag TMA SDK script and triggering Rewarded Interstitial / Video ads
 * via window.show_XXXXXXX() to generate real publisher revenue on every ad view.
 */

// Default Monetag Zone ID (can be overridden via VITE_MONETAG_ZONE_ID)
const DEFAULT_ZONE_ID = (import.meta.env.VITE_MONETAG_ZONE_ID as string) || '11624183';

let sdkScriptLoaded = false;
let sdkLoadPromise: Promise<boolean> | null = null;

/**
 * Ensures the Monetag TMA SDK tag is dynamically loaded and ready in the document.
 */
export function initMonetagTmaSdk(zoneId: string = DEFAULT_ZONE_ID): Promise<boolean> {
  if (sdkScriptLoaded) return Promise.resolve(true);
  if (sdkLoadPromise) return sdkLoadPromise;

  sdkLoadPromise = new Promise((resolve) => {
    // Check if show_ function already exists
    const existingFn = Object.keys(window).find((k) => k.startsWith('show_'));
    if (existingFn && typeof (window as any)[existingFn] === 'function') {
      sdkScriptLoaded = true;
      resolve(true);
      return;
    }

    // Create Monetag SDK script
    const script = document.createElement('script');
    script.src = 'https://alwingulla.com/88/tag.min.js';
    script.dataset.zone = zoneId;
    script.async = true;
    (script as any)['data-cfasync'] = 'false';

    script.onload = () => {
      console.log(`[MONETAG TMA SDK]: Script loaded successfully for Zone ${zoneId}.`);
      sdkScriptLoaded = true;
      resolve(true);
    };

    script.onerror = (e) => {
      console.warn('[MONETAG TMA SDK]: Failed to load alwingulla.com tag script, trying fallback domain...', e);
      // Fallback to secondary Monetag CDN domain
      const fallbackScript = document.createElement('script');
      fallbackScript.src = 'https://nap5k.com/tag.min.js';
      fallbackScript.dataset.zone = zoneId;
      fallbackScript.async = true;
      fallbackScript.onload = () => {
        sdkScriptLoaded = true;
        resolve(true);
      };
      fallbackScript.onerror = () => {
        console.error('[MONETAG TMA SDK]: Both primary and fallback SDK scripts failed to load.');
        resolve(false);
      };
      document.head.appendChild(fallbackScript);
    };

    document.head.appendChild(script);
  });

  return sdkLoadPromise;
}

/**
 * Triggers a real, paid Monetag Rewarded Interstitial / Video Ad.
 * Returns a Promise that resolves ONLY when the user has fully watched the ad.
 * 
 * @param ymid Optional tracking identifier (e.g. userId)
 * @param zoneId Optional custom Zone ID
 */
export async function showMonetagRewardedAd(ymid?: string, zoneId: string = DEFAULT_ZONE_ID): Promise<boolean> {
  await initMonetagTmaSdk(zoneId);

  // Find the global show function (e.g. window.show_11624183 or window.show_...)
  const targetFnName = `show_${zoneId}`;
  let showFn = (window as any)[targetFnName];

  if (!showFn || typeof showFn !== 'function') {
    // Search for any active show_ function generated by Monetag
    const foundFnName = Object.keys(window).find((k) => k.startsWith('show_') && typeof (window as any)[k] === 'function');
    if (foundFnName) {
      showFn = (window as any)[foundFnName];
    }
  }

  if (!showFn || typeof showFn !== 'function') {
    throw new Error('MONETAG_NOT_READY');
  }

  try {
    console.log(`[MONETAG TMA SDK]: Triggering paid rewarded ad via ${showFn.name || targetFnName}...`);
    // Call official Monetag show function
    const adOptions: any = ymid ? { ymid, type: 'rewarded' } : { type: 'rewarded' };
    const promiseOrRes = showFn(adOptions) || showFn();
    if (promiseOrRes && typeof promiseOrRes.then === 'function') {
      await promiseOrRes;
    }
    console.log('[MONETAG TMA SDK]: Paid Rewarded Ad successfully completed! Publisher revenue credited.');
    return true;
  } catch (error) {
    console.error('[MONETAG TMA SDK]: Ad failed or was dismissed early:', error);
    throw error;
  }
}
